name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
